+require: rubocop-rails

 AllCops:
   Exclude:
     - bin/**/*
     - db/schema.rb
     - .gemspec/**/*
     - .bundle/**/*
     - vendor/**/*
     - '**/dummy**/*'
     - !ruby/regexp /old_and_unused\.rb$/

 Rails/NotNullColumn:
   Enabled: false
